### ISSUE TITLE
Error running the application locally.

### ISSUE THREAD

**Issue by mujtabasiddiqui0786** [lestercardoz11/basic-ecommerce#2]
# After following the set of instruction, the application is not running.
below is the error -

### Error - 
PHP Fatal error:  Uncaught Error: Call to undefined function CodeIgniter\locale_set_default() in /basic-ecommerce/system/CodeIgniter.php:184
Stack trace:
#0 /basic-ecommerce/system/bootstrap.php(181): CodeIgniter\CodeIgniter->initialize()
#1 /basic-ecommerce/spark(44): require('/home/aqsa/Desk...')
#2 {main}
  thrown in /basic-ecommerce/system/CodeIgniter.php on line 184

**Comment by mujtabasiddiqui0786** [comment]
I found my temporary solution in without updating the PHP Version in Xampp.

Go to C:\xampp\htdocs\projectfolder\system\CodeIgniter.php - line 184 and change the next line.

Before:

```locale_set_default($this->config->defaultLocale` ?? 'en');```
After:

```
if( function_exists('locale_set_default' ) ) :
   locale_set_default($this->config->defaultLocale ?? 'en');
    endif;

**Comment by lestercardoz11** [comment]
I haven't really been working working PHP for a long time now.
But thanks for this, I'll push the fix
